### ISSUE TITLE
External notebook uses legacy code

### ISSUE THREAD

**Issue by frenkcleven** [acorbe/sociophysicsDataHandler#5]
Hi guys,

[This notebook](https://colab.research.google.com/drive/1xHR6guJqnSf02hxIgrHGw944YbLU7JGA#scrollTo=nnEIMkWe80G-), which is referred to in step 9 of the tools manual, still uses the `fetch_data_from_path` function which has been replaced by `fetch_prorail_data_from_path` and `fetch_depth_data_from_path`. I can't see who is the owner of this notebook.

**Comment by c-pouw** [comment]
Hi Frenk, thanks for the heads up. It should be fixed now.
